name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  
jobs: 
  BuildAndPush:
    runs-on: ubuntu-latest
    steps:
    #- uses: actions/checkout@v4
    #- name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag my-image-name:${{ github.sha }}
    - uses: actions/checkout@v4
    - name: Create npm cache
      uses: actions/setup-node@v4
      with:
        node-version: 20.18.3
        cache: 'npm'
    - run: npm install
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: luis.delgado13@inacapmail.cl
        password: ${{ secrets.TOKEN }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v6.15.0
      with:
        file: Dockerfile
        push: true
        #tags: name/app:latest,name/app:1.0.0
        tags: |
          ghcr.io/luisdelgado-ld/frontend:latest
          ghcr.io/luisdelgado-ld/frontend:${{ github.sha	}}

        github-token: ${{ secrets.TOKEN }}
