name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  token: ${{ secrets.TOKEN }}

  
jobs:
  build and push:
    runs-on: ubuntu-latest
    steps:
    #- uses: actions/checkout@v4
    #- name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag my-image-name:${{ github.sha }}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: luisdelgado-ld
        password: ${{ token }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v6.15.0
      with:
        file: Dockerfile
        provenance: true
        push: true
        #tags: name/app:latest,name/app:1.0.0
        tags: |
          ${{ github.repository	}}:latest
          ${{ github.repository	}}:${{ github.run_id	}}
          ${{ github.repository	}}:${{ github.sha	}}

        github-token: ${{ secrets.TOKEN }}
